server:
  port: 8080
  tomcat:
    compression: on

spring:
  datasource:
    url: ${database:jdbc:mysql://localhost/expenses}
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
